/**
 * Distritos de Lima Metropolitana y Callao. Es la base de distritos para el
 * selector de entrega; la cobertura real (tarifa, mínimo y horario) la define
 * la tienda en `delivery_zones`.
 */
export const DELIVERY_DISTRICTS: readonly string[] = [
  "Ancón",
  "Ate",
  "Barranco",
  "Bellavista",
  "Breña",
  "Callao",
  "Carabayllo",
  "Carmen de la Legua Reynoso",
  "Chaclacayo",
  "Chorrillos",
  "Cieneguilla",
  "Comas",
  "Cercado de Lima",
  "El Agustino",
  "Independencia",
  "Jesús María",
  "La Molina",
  "La Perla",
  "La Punta",
  "La Victoria",
  "Lince",
  "Los Olivos",
  "Lurigancho (Chosica)",
  "Lurín",
  "Magdalena del Mar",
  "Mi Perú",
  "Miraflores",
  "Pachacámac",
  "Pueblo Libre",
  "Puente Piedra",
  "Pucusana",
  "Punta Hermosa",
  "Punta Negra",
  "Rímac",
  "San Bartolo",
  "San Borja",
  "San Isidro",
  "San Juan de Lurigancho",
  "San Juan de Miraflores",
  "San Luis",
  "San Martín de Porres",
  "San Miguel",
  "Santa Anita",
  "Santa María del Mar",
  "Santa Rosa",
  "Santiago de Surco",
  "Surquillo",
  "Ventanilla",
  "Villa El Salvador",
  "Villa María del Triunfo",
] as const;
